// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-GmArVvDX4dK7FyITutfiN298r2yk94',
    appId: '1:809995362596:web:a7584f42645534771013b1',
    messagingSenderId: '809995362596',
    projectId: 'launchhub-alielchab',
    authDomain: 'launchhub-alielchab.firebaseapp.com',
    storageBucket: 'launchhub-alielchab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD53dtbZ6qUOPsqbrSy09_5TRWJbK6urmA',
    appId: '1:809995362596:android:146ae24bd32432b11013b1',
    messagingSenderId: '809995362596',
    projectId: 'launchhub-alielchab',
    storageBucket: 'launchhub-alielchab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmWTow2Xvb9CEBzMKuKiiI6vSfW9e0JNY',
    appId: '1:809995362596:ios:c665bf3679f6cfd71013b1',
    messagingSenderId: '809995362596',
    projectId: 'launchhub-alielchab',
    storageBucket: 'launchhub-alielchab.appspot.com',
    iosBundleId: 'com.example.launchhubFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmWTow2Xvb9CEBzMKuKiiI6vSfW9e0JNY',
    appId: '1:809995362596:ios:8a264736b514da011013b1',
    messagingSenderId: '809995362596',
    projectId: 'launchhub-alielchab',
    storageBucket: 'launchhub-alielchab.appspot.com',
    iosBundleId: 'com.example.launchhubFrontend.RunnerTests',
  );
}
