<?php

namespace Database\Seeders;

use App\Models\Industry;
use App\Models\Skill;
use App\Models\Specialization;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SkillsTableSeeder extends Seeder
{
    public function run()
    {

        $skills = [
            "General" => [
                "Communication",
                "Teamwork",
                "Problem Solving",
                "Time Management",
                "Leadership",
                "Creativity",
                "Interpersonal Skills",
                "Adaptability",
                "Collaboration",
                "Critical Thinking",
                "Decision Making",
                "Negotiation",
                "Persuasion",
                "Stress Management",
                "Emotional Intelligence",
            ],
            "Software Development" => [
                "Algorithm Design",
                "Object-Oriented Programming",
                "Version Control (Git)",
                "Database Management",
                "Debugging Techniques",
                "API Development",
                "Code Optimization",
                "Software Testing (Unit, Integration)",
                "Design Patterns",
                "DevOps Practices",
                "Security Best Practices",
                "Responsive Design",
                "Cross-Platform Development",
                "Documentation Skills",
                "Agile Methodologies"
            ],
            "Cybersecurity" => [
                "Network Security",
                "Ethical Hacking",
                "Risk Management",
                "Incident Response",
                "Cryptography",
                "Firewall Management",
                "Penetration Testing",
                "Compliance and Auditing",
                "Threat Intelligence",
                "Security Information and Event Management (SIEM)",
                "Vulnerability Assessment",
                "Intrusion Detection Systems",
                "Data Privacy Laws",
                "Cloud Security",
                "Mobile Security"
            ],
            "Data Science" => [
                "Statistical Analysis",
                "Machine Learning",
                "Data Wrangling",
                "Data Visualization",
                "Predictive Modeling",
                "Big Data Technologies",
                "Programming (Python/R)",
                "Database Querying (SQL)",
                "Data Mining",
                "Experimental Design",
                "Natural Language Processing",
                "Cloud Tools for Data Science",
                "Business Intelligence",
                "Deep Learning",
                "Data Governance"
            ],
            "AI & Machine Learning'" => [
                "Neural Networks",
                "Deep Learning Frameworks (TensorFlow, PyTorch)",
                "Computer Vision",
                "Natural Language Processing",
                "Reinforcement Learning",
                "Predictive Modeling",
                "Algorithm Tuning",
                "Data Preprocessing",
                "Feature Engineering",
                "AI Ethics and Bias",
                "Model Deployment",
                "Big Data Integration",
                "Cloud AI Services",
                "Robotics",
                "Quantum Machine Learning"
            ],
            "Cloud Computing" => [
                "AWS/Azure/GCP Services",
                "Cloud Infrastructure",
                "Cloud Security",
                "Containerization (Docker, Kubernetes)",
                "Serverless Architecture",
                "DevOps in the Cloud",
                "Cloud Storage Solutions",
                "Cloud Networking",
                "Cloud Application Deployment",
                "Cloud Cost Optimization",
                "Hybrid Cloud Environments",
                "Cloud Monitoring Tools",
                "API Management in the Cloud",
                "Cloud Compliance and Regulations",
                "Multi-Cloud Strategies"
            ],
            "Network Engineering" => [
                "Network Design",
                "Router and Switch Configuration",
                "Network Protocols (TCP/IP)",
                "Wireless Technologies",
                "Network Security",
                "VPN Management",
                "Network Troubleshooting",
                "Performance Tuning",
                "VoIP Technologies",
                "Cloud Networking",
                "Network Automation",
                "Software-Defined Networking",
                "Fiber Optics",
                "Network Monitoring Tools",
                "IPv4/IPv6"
            ],
            "UI/UX Design" => [
                "User Research",
                "Wireframing and Prototyping",
                "Visual Design Principles",
                "Interaction Design",
                "Usability Testing",
                "Responsive Web Design",
                "Information Architecture",
                "User-Centered Design",
                "Accessibility Standards",
                "Design Tools (Sketch, Figma)",
                "Graphic Design Skills",
                "Motion Design",
                "Brand Identity Design",
                "Typography",
                "Color Theory"
            ],
            "Mobile App Development'" => [
                "iOS Development (Swift)",
                "Android Development (Kotlin/Java)",
                "Cross-Platform Development (Flutter, React Native)",
                "Mobile UI Design",
                "API Integration",
                "Mobile Security",
                "Performance Optimization",
                "App Store Deployment",
                "Backend Development for Mobile",
                "Mobile Analytics",
                "Gesture and Touch Recognition",
                "Local Storage and Caching",
                "Mobile Testing",
                "Bluetooth Technology",
                "Augmented Reality"
            ],
            "Game Development" => [
                "Game Engine Expertise (Unity, Unreal Engine)",
                "3D Modeling and Animation",
                "Game Physics",
                "Scripting (C#, C++)",
                "Level Design",
                "AI in Gaming",
                "Virtual Reality",
                "Multiplayer Game Setup",
                "Sound Design",
                "Game Testing and Debugging",
                "User Interface Design for Games",
                "Game Monetization Strategies",
                "Cross-Platform Game Development",
                "Narrative Design",
                "Graphics Programming"
            ],
            "IT Project Management" => [
                "Agile and Scrum Methodologies",
                "Risk Management",
                "Project Scheduling",
                "Budgeting and Cost Management",
                "Stakeholder Management",
                "Quality Management",
                "Resource Allocation",
                "Communication Skills",
                "Technical Documentation",
                "Change Management",
                "Project Lifecycle Management",
                "IT Governance",
                "Vendor Management",
                "Team Leadership",
                "Project Recovery"
            ],
            "Nursing" => [
                "Patient Assessment",
                "Wound Care",
                "Medication Administration",
                "Patient Education",
                "Emergency Care",
                "Infection Control",
                "Electronic Health Records (EHR)",
                "Compassionate Care",
                "Critical Thinking",
                "Time Management",
                "Team Collaboration",
                "Evidence-Based Practice",
                "Patient Advocacy",
                "IV Therapy",
                "Health Promotion"
            ],
            "General Medicine" => [
                "Clinical Diagnosis",
                "Patient Management",
                "Medical Procedures",
                "Preventive Healthcare",
                "Chronic Disease Management",
                "Pharmacotherapy",
                "Health Education",
                "Emergency Medicine",
                "Clinical Research",
                "Healthcare Ethics",
                "Communication Skills",
                "Electronic Medical Records",
                "Cultural Competency",
                "Telemedicine",
                "Disease Surveillance"
            ],
            "Dentistry" => [
                "Oral Diagnosis",
                "Operative Dentistry",
                "Periodontics",
                "Endodontics",
                "Prosthodontics",
                "Oral Surgery",
                "Orthodontics",
                "Pediatric Dentistry",
                "Radiography Interpretation",
                "Patient Education",
                "Infection Control",
                "Dental Materials Knowledge",
                "Pain Management",
                "Cosmetic Dentistry",
                "Dental Practice Management"
            ],
            "Pediatrics" => [
                "Childhood Disease Diagnosis",
                "Vaccinations",
                "Growth and Development Monitoring",
                "Pediatric Emergencies",
                "Neonatal Care",
                "Adolescent Medicine",
                "Child Advocacy",
                "Pediatric Nutrition",
                "Behavioral Counseling",
                "Developmental Disorders",
                "Childhood Obesity Management",
                "Pediatric Surgery Coordination",
                "Allergy and Asthma Management",
                "Pediatric Medication Dosing",
                "Family Education"
            ],
            "Radiology" => [
                "Diagnostic Imaging",
                "Computed Tomography (CT)",
                "Magnetic Resonance Imaging (MRI)",
                "Ultrasound Imaging",
                "Radiation Safety",
                "Interventional Radiology",
                "Nuclear Medicine",
                "Mammography",
                "Image Interpretation",
                "Pediatric Radiology",
                "Oncologic Imaging",
                "Radiographic Positioning",
                "Radiology Information Systems",
                "Quality Control in Radiology",
                "Contrast Media Administration"
            ],
            "Pharmacology" => [
                "Drug Mechanism of Action",
                "Pharmacokinetics and Pharmacodynamics",
                "Drug Interactions",
                "Medication Therapy Management",
                "Clinical Pharmacology",
                "Toxicology",
                "Prescription Dispensing",
                "Patient Counseling",
                "Drug Development",
                "Regulatory Compliance",
                "Pharmacogenomics",
                "Biopharmaceuticals",
                "Over-the-Counter Medications",
                "Pharmacy Operations",
                "Pharmacoepidemiology"
            ],
            "Biomedical Engineering" => [
                "Medical Device Design",
                "Biomechanics",
                "Biomaterials",
                "Tissue Engineering",
                "Bioinstrumentation",
                "Clinical Engineering",
                "Medical Imaging Technology",
                "Rehabilitation Engineering",
                "Healthcare Informatics",
                "Regulatory Affairs",
                "Biomedical Signal Processing",
                "Artificial Organs",
                "Orthopedic Bioengineering",
                "Biomedical Research",
                "Systems Physiology"
            ],
            "Healthcare Administration" => [
                "Healthcare Policy and Law",
                "Financial Management in Healthcare",
                "Healthcare Quality Improvement",
                "Human Resources Management",
                "Strategic Planning",
                "Healthcare Marketing",
                "Patient Safety",
                "Health Information Systems",
                "Ethical Decision Making",
                "Leadership in Healthcare",
                "Healthcare Economics",
                "Facility Management",
                "Regulatory Compliance",
                "Risk Management",
                "Healthcare Analytics"
            ],
            "Physical Therapy" => [
                "Patient Assessment",
                "Therapeutic Exercise",
                "Manual Therapy",
                "Pain Management",
                "Neurological Rehabilitation",
                "Orthopedic Rehabilitation",
                "Pediatric Physical Therapy",
                "Cardiopulmonary Rehabilitation",
                "Gait Training",
                "Sports Injury Rehabilitation",
                "Electrotherapy",
                "Evidence-Based Practice",
                "Mobility Aids",
                "Post-Surgical Rehabilitation",
                "Chronic Pain Management"
            ],
            "Mental Health Services" => [
                "Cognitive Behavioral Therapy",
                "Crisis Intervention",
                "Psychotherapy",
                "Psychiatric Medication Management",
                "Group Therapy",
                "Family Counseling",
                "Substance Abuse Counseling",
                "Mindfulness Techniques",
                "Stress Management",
                "Behavioral Assessment",
                "Trauma-Informed Care",
                "Mental Health Education",
                "Play Therapy",
                "Eating Disorder Management",
                "Suicide Prevention"
            ],
            "Investment Banking" => [
                "Mergers and Acquisitions",
                "Financial Modeling",
                "Capital Markets Knowledge",
                "Deal Structuring",
                "Due Diligence",
                "Valuation Techniques",
                "Client Relationship Management",
                "Regulatory Knowledge",
                "Risk Analysis",
                "Securities Trading"
            ],
            "Accounting" => [
                "Financial Reporting",
                "General Ledger Management",
                "Auditing",
                "Account Reconciliation",
                "Budgeting",
                "Tax Preparation",
                "Accounts Payable/Receivable",
                "Cost Accounting",
                "GAAP Compliance",
                "Financial Analysis"
            ],
            "Financial Planning" => [
                "Budgeting and Forecasting",
                "Retirement Planning",
                "Investment Strategies",
                "Risk Assessment",
                "Tax Planning",
                "Estate Planning",
                "Wealth Preservation",
                "Debt Management",
                "Insurance Planning",
                "Client Advising"
            ],
            "Insurance" => [
                "Risk Assessment",
                "Policy Underwriting",
                "Claims Handling",
                "Insurance Product Knowledge",
                "Customer Service",
                "Regulatory Compliance",
                "Actuarial Analysis",
                "Sales and Marketing",
                "Fraud Detection",
                "Negotiation Skills"
            ],
            "Corporate Finance" => [
                "Capital Budgeting",
                "Financial Statement Analysis",
                "Cash Flow Management",
                "Corporate Valuation",
                "Capital Raising",
                "Financial Forecasting",
                "Mergers and Acquisitions",
                "Investor Relations",
                "Treasury Management",
                "Strategic Planning"
            ],
            "Financial Analysis" => [
                "Data Analysis",
                "Financial Reporting",
                "Budget Analysis",
                "Market Trend Analysis",
                "Variance Analysis",
                "Cost-Benefit Analysis",
                "Investment Analysis",
                "Financial Modeling",
                "Performance Metrics",
                "Forecasting"
            ],
            "Tax Advisory" => [
                "Tax Compliance",
                "Tax Planning",
                "International Tax",
                "Corporate Tax",
                "Tax Research",
                "Estate Tax Planning",
                "IRS Regulations Knowledge",
                "Tax Software Proficiency",
                "State and Local Taxes",
                "Tax Strategy"
            ],
            "Risk Management" => [
                "Risk Analysis",
                "Compliance Monitoring",
                "Financial Risk Assessment",
                "Operational Risk Control",
                "Risk Mitigation Strategies",
                "Insurance Knowledge",
                "Credit Risk Analysis",
                "Market Risk Analysis",
                "Regulatory Compliance",
                "Audit Procedures"
            ],
            "Wealth Management" => [
                "Asset Allocation",
                "Portfolio Management",
                "Financial Planning",
                "Client Relationship Management",
                "Estate Planning",
                "Investment Strategy",
                "Tax Planning",
                "Risk Management",
                "Retirement Planning",
                "Market Analysis"
            ],
            "Regulatory Compliance" => [
                "Legal Compliance",
                "Regulatory Reporting",
                "Compliance Audit",
                "Policy Development",
                "Risk Assessment",
                "Ethics Management",
                "Data Privacy",
                "Anti-Money Laundering",
                "Corporate Governance",
                "Compliance Training"
            ],
            "Early Childhood Education" => [
                "Child Development Knowledge",
                "Classroom Management",
                "Lesson Planning",
                "Play-Based Learning",
                "Observation and Assessment",
                "Parent Communication",
                "Inclusive Education",
                "Creative Arts Integration",
                "Behavioral Management",
                "Early Literacy and Numeracy"
            ],
            "Special Education" => [
                "Individualized Education Plans (IEP)",
                "Behavioral Intervention Techniques",
                "Inclusive Classroom Strategies",
                "Adaptive Learning Technologies",
                "Assessment and Evaluation",
                "Collaboration with Therapists",
                "Differentiated Instruction",
                "Disability Awareness",
                "Communication Aids Proficiency",
                "Emotional and Social Support"
            ],
            "Curriculum Development" => [
                "Educational Research",
                "Instructional Design",
                "Standards-Based Curriculum",
                "Educational Psychology",
                "Assessment Design",
                "Professional Development",
                "Technology Integration",
                "Subject Matter Expertise",
                "Learning Theories Application",
                "Curriculum Mapping"
            ],
            "Educational Administration" => [
                "Leadership and Management",
                "Educational Policy",
                "School Finance and Budgeting",
                "Staff Development and Training",
                "School Operations Management",
                "Academic Counseling",
                "Community Engagement",
                "Legal and Ethical Compliance",
                "Data-Driven Decision Making",
                "Crisis Management"
            ],
            "Tutoring" => [
                "Subject Matter Expertise",
                "One-on-One Instruction",
                "Learning Style Adaptation",
                "Motivational Skills",
                "Assessment and Feedback",
                "Curriculum Knowledge",
                "Time Management",
                "Resource Development",
                "Student Engagement Strategies",
                "Progress Monitoring"
            ],
            "E-Learning" => [
                "Instructional Design",
                "Learning Management Systems (LMS)",
                "Multimedia Content Creation",
                "Online Assessment Techniques",
                "Virtual Classroom Management",
                "Digital Communication",
                "Adaptive Learning Technologies",
                "E-Learning Platforms Proficiency",
                "Course Development",
                "Webinar Facilitation"
            ],
            "Higher Education" => [
                "Academic Advising",
                "Research and Publication",
                "Course Design and Delivery",
                "Student Engagement",
                "Higher Education Policy",
                "Diversity and Inclusion",
                "Grant Writing",
                "Departmental Collaboration",
                "Academic Assessment",
                "Professional Development"
            ],
            "Educational Technology" => [
                "Technology Integration in Classroom",
                "Interactive Learning Tools",
                "Educational Software Proficiency",
                "Digital Literacy",
                "Online Learning Platforms",
                "Data Analytics in Education",
                "Multimedia Production",
                "Emerging Educational Technologies",
                "Instructional Design",
                "Cybersecurity in Education"
            ],
            "Literacy Program Coordination" => [
                "Reading and Writing Instruction",
                "Program Development and Evaluation",
                "Community Outreach",
                "Volunteer Management",
                "Funding and Grant Writing",
                "Curriculum Design for Literacy",
                "Student Assessment",
                "Educational Partnerships",
                "Resource Allocation",
                "Data-Driven Literacy Strategies"
            ],
            "Career Counseling" => [
                "Career Assessment Tools",
                "Resume and Cover Letter Assistance",
                "Interview Preparation",
                "Job Search Strategies",
                "Career Development Theories",
                "Networking Techniques",
                "Professional Development Planning",
                "Labor Market Trends",
                "Educational Pathways Guidance",
                "Personal Branding"
            ],
            "Quality Control" => [
                "Statistical Process Control",
                "Quality Assurance Standards",
                "Inspection Techniques",
                "Process Improvement",
                "ISO Standards Compliance",
                "Quality Auditing",
                "Root Cause Analysis",
                "Product Testing",
                "Quality Management Systems",
                "Continuous Improvement"
            ],
            "Supply Chain Management" => [
                "Logistics Planning",
                "Inventory Management",
                "Procurement",
                "Supplier Relationship Management",
                "Demand Forecasting",
                "Supply Chain Optimization",
                "Risk Management",
                "Sustainability Practices",
                "Transportation Management",
                "Warehouse Operations"
            ],
            "Industrial Engineering" => [
                "Process Optimization",
                "Systems Analysis",
                "Work Study",
                "Facility Layout Design",
                "Production Planning",
                "Ergonomics and Human Factors",
                "Cost Analysis",
                "Quality Control",
                "Project Management",
                "Operations Research"
            ],
            "Product Design" => [
                "Concept Development",
                "3D Modeling",
                "Prototyping",
                "Design Thinking",
                "User-Centered Design",
                "Material Selection",
                "CAD Software",
                "Sustainability Considerations",
                "Ergonomics",
                "Product Testing and Analysis"
            ],
            "Plant Management" => [
                "Production Oversight",
                "Equipment Maintenance",
                "Safety Standards Compliance",
                "Team Leadership",
                "Budget Management",
                "Process Improvement",
                "Workforce Scheduling",
                "Quality Assurance",
                "Inventory Control",
                "Regulatory Compliance"
            ],
            "Operations Research" => [
                "Mathematical Modeling",
                "Data Analysis",
                "Optimization Techniques",
                "Simulation Modeling",
                "Decision Analysis",
                "Supply Chain Analysis",
                "Risk Assessment",
                "Statistical Analysis",
                "Algorithm Development",
                "Predictive Modeling"
            ],
            "Lean Manufacturing" => [
                "Waste Reduction",
                "Continuous Improvement",
                "Value Stream Mapping",
                "Kaizen",
                "5S Methodology",
                "Just-In-Time Production",
                "Root Cause Analysis",
                "Process Standardization",
                "Efficiency Optimization",
                "Team Empowerment"
            ],
            "Safety Management" => [
                "Hazard Identification",
                "Regulatory Compliance",
                "Safety Training",
                "Emergency Response Planning",
                "Risk Assessment",
                "Incident Investigation",
                "Occupational Health",
                "Safety Audits",
                "Personal Protective Equipment",
                "Environmental Safety"
            ],
            "Process Engineering" => [
                "Process Design and Optimization",
                "Chemical Engineering Principles",
                "P&ID Development",
                "Equipment Specification",
                "Process Simulation",
                "Troubleshooting",
                "Continuous Improvement",
                "Safety and Environmental Regulations",
                "Scale-Up",
                "Process Control"
            ],
            "Maintenance Supervision" => [
                "Equipment Maintenance Strategies",
                "Team Leadership",
                "Preventive Maintenance",
                "Safety Compliance",
                "Budget Management",
                "Downtime Reduction",
                "Maintenance Scheduling",
                "Reliability Engineering",
                "Facility Management",
                "Technical Troubleshooting"
            ],
            "Store Management" => [
                "Staff Training and Supervision",
                "Sales Target Achievement",
                "Customer Relationship Management",
                "Inventory Control",
                "Store Operations",
                "Financial Management",
                "Visual Merchandising",
                "Loss Prevention Strategies",
                "Performance Analysis",
                "Compliance and Regulations"
            ],
            "Merchandising" => [
                "Product Assortment Planning",
                "Trend Analysis",
                "Pricing Strategies",
                "Supplier Negotiation",
                "Inventory Management",
                "Visual Merchandising",
                "Sales Forecasting",
                "Market Research",
                "Brand Alignment",
                "Promotional Campaigns"
            ],
            "Retail Buying" => [
                "Vendor Management",
                "Purchase Order Management",
                "Market Trend Analysis",
                "Negotiation Skills",
                "Inventory Turnover",
                "Budget Management",
                "Product Selection",
                "Supply Chain Coordination",
                "Quality Control",
                "Sustainable Sourcing"
            ],
            "Sales Strategy" => [
                "Market Analysis",
                "Sales Forecasting",
                "Customer Segmentation",
                "Channel Strategy",
                "Pricing Strategy",
                "Sales Promotion Planning",
                "Competitive Analysis",
                "Sales Process Optimization",
                "CRM Software Proficiency",
                "Team Leadership"
            ],
            "Customer Service" => [
                "Client Communication",
                "Problem Resolution",
                "Product Knowledge",
                "Customer Feedback Analysis",
                "Empathy and Patience",
                "Conflict Resolution",
                "Sales Techniques",
                "Customer Retention Strategies",
                "CRM Systems",
                "Service Standards Development"
            ],
            "E-Commerce" => [
                "Online Store Management",
                "Digital Marketing",
                "Web Analytics",
                "Customer Experience Optimization",
                "E-commerce Platforms",
                "SEO/SEM",
                "Payment Gateway Management",
                "Social Media Management",
                "Logistics Coordination",
                "Data Security and Privacy"
            ],
            "Visual Merchandising" => [
                "Display Design",
                "Brand Representation",
                "Store Layout Planning",
                "Creative Visual Concepts",
                "Trend Awareness",
                "Customer Engagement Strategies",
                "Merchandise Presentation",
                "Space Utilization",
                "Lighting and Signage",
                "Window Display Design"
            ],
            "Supply Chain Coordination" => [
                "Vendor Relations",
                "Logistics Management",
                "Inventory Control",
                "Demand Forecasting",
                "Supply Planning",
                "Transportation Management",
                "Cost Reduction",
                "Compliance Monitoring",
                "Process Improvement",
                "Technology Integration"
            ],
            "Brand Promotion" => [
                "Marketing Campaigns",
                "Social Media Strategy",
                "Public Relations",
                "Event Planning and Execution",
                "Customer Engagement",
                "Brand Messaging",
                "Market Research",
                "Content Creation",
                "Influencer Partnerships",
                "Cross-Channel Marketing"
            ],
            "Inventory Management" => [
                "Stock Control",
                "Demand Forecasting",
                "Inventory Analysis",
                "Purchasing",
                "Warehouse Management",
                "Stock Replenishment",
                "Inventory Turnover Optimization",
                "Loss Prevention",
                "Supply Chain Coordination",
                "Data-Driven Decision Making"
            ],
            "Project Management" => [
                "Scope and Requirement Analysis",
                "Budget Planning and Management",
                "Team Leadership",
                "Risk Management",
                "Communication Skills",
                "Stakeholder Management",
                "Scheduling and Time Management",
                "Quality Control",
                "Agile and Waterfall Methodologies",
                "Problem Solving"
            ],
            "Civil Engineering" => [
                "Structural Analysis",
                "Site Development and Planning",
                "Construction Management",
                "Sustainable Design",
                "Geotechnical Engineering",
                "Hydraulic Engineering",
                "Transportation Engineering",
                "Environmental Impact Assessment",
                "Building Codes and Regulations",
                "Project Coordination"
            ],
            "Architecture" => [
                "Design Conceptualization",
                "Technical Drawing and Drafting",
                "3D Modeling",
                "Sustainable Design",
                "Building Codes Compliance",
                "Client Consultation",
                "Project Presentation",
                "Materials Knowledge",
                "Construction Documentation",
                "Historical Context Understanding"
            ],
            "Cost Estimation" => [
                "Budget Development",
                "Cost Analysis",
                "Material and Labor Costing",
                "Risk Assessment",
                "Bid Preparation",
                "Value Engineering",
                "Financial Reporting",
                "Project Scope Analysis",
                "Cost Monitoring",
                "Software Proficiency (e.g., CostX, Planswift)"
            ],
            "Site Supervision" => [
                "Construction Site Management",
                "Safety Regulation Enforcement",
                "Quality Assurance",
                "Team Coordination",
                "Project Scheduling",
                "Resource Allocation",
                "Problem Resolution",
                "Progress Reporting",
                "Subcontractor Management",
                "Compliance Monitoring"
            ],
            "Safety Regulation Compliance" => [
                "Occupational Safety Standards",
                "Risk Assessment",
                "Safety Training",
                "Incident Investigation",
                "Regulatory Compliance",
                "Emergency Response Planning",
                "Safety Audits",
                "PPE Management",
                "Hazard Analysis",
                "Environmental Safety"
            ],
            "Sustainability Design" => [
                "Green Building Practices",
                "LEED Certification Knowledge",
                "Energy Efficiency Planning",
                "Sustainable Material Selection",
                "Environmental Impact Analysis",
                "Water Conservation Strategies",
                "Carbon Footprint Reduction",
                "Renewable Energy Integration",
                "Eco-friendly Design Techniques",
                "Sustainable Urban Development"
            ],
            "Urban Planning" => [
                "Land Use Planning",
                "Community Engagement",
                "Zoning and Regulations",
                "Transportation Planning",
                "Environmental Sustainability",
                "Urban Design",
                "Public Policy Development",
                "GIS Proficiency",
                "Demographic Analysis",
                "Infrastructure Planning"
            ],
            "Construction Law" => [
                "Contract Negotiation and Management",
                "Dispute Resolution",
                "Legal Compliance",
                "Risk Management",
                "Building Regulations Knowledge",
                "Construction Claims",
                "Labor Law",
                "Insurance and Liability",
                "Permitting Process",
                "Industry Standard Practices"
            ],
            "Interior Design" => [
                "Space Planning",
                "Material and Finish Selection",
                "Color Theory",
                "Client Consultation",
                "3D Rendering",
                "Furniture Design",
                "Lighting Design",
                "Trend Forecasting",
                "Project Budgeting",
                "CAD Software Proficiency"
            ],
            "Renewable Energy" => [
                "Solar Energy Systems",
                "Wind Energy Technology",
                "Sustainable Development",
                "Energy Policy and Regulation",
                "Project Management in Renewables",
                "Energy Storage Solutions",
                "Grid Integration",
                "Environmental Impact Assessment",
                "Renewable Energy Finance",
                "Public Awareness and Education"
            ],
            "Petroleum Engineering" => [
                "Reservoir Engineering",
                "Drilling Engineering",
                "Production Technology",
                "Well Log Interpretation",
                "Oil and Gas Exploration",
                "Fluid Mechanics",
                "Offshore Operations",
                "Safety and Environmental Management",
                "Petroleum Geology",
                "Project Economics"
            ],
            "Energy Efficiency Consulting" => [
                "Energy Audit",
                "Sustainability Solutions",
                "Building Systems Analysis",
                "Energy Conservation Measures",
                "Utility Bill Analysis",
                "Carbon Footprint Reduction",
                "Renewable Energy Options",
                "Regulatory Compliance",
                "Client Advising",
                "Energy Performance Contracting"
            ],
            "Solar Energy System Design" => [
                "Photovoltaic System Design",
                "Energy Analysis",
                "Solar Technology",
                "System Sizing and Optimization",
                "CAD for Solar Design",
                "Electrical Engineering",
                "Permitting and Compliance",
                "Financial Analysis",
            ],
            "Wind Turbine Engineering" => [
                "Aerodynamics",
                "Structural Design",
                "Wind Resource Assessment",
                "Turbine Maintenance",
                "Renewable Energy Technologies",
                "Project Development",
                "Grid Integration",
                "Safety Standards",
                "Performance Analysis",
                "Environmental Impact"
            ],
            "Nuclear Power Management" => [
                "Nuclear Reactor Operation",
                "Radiation Safety",
                "Regulatory Compliance",
                "Waste Management",
                "Nuclear Physics",
                "Emergency Preparedness",
                "Plant Maintenance",
                "Thermal Hydraulics",
                "Fuel Cycle Analysis",
                "Quality Assurance"
            ],
            "Power Grid Control" => [
                "Electrical Grid Operations",
                "Energy Distribution",
                "Grid Stability and Reliability",
                "Smart Grid Technologies",
                "Demand Response Management",
                "Utility Systems",
                "Regulatory Standards",
                "Renewable Integration",
                "System Monitoring",
                "Blackout Prevention"
            ],
            "Environmental Compliance" => [
                "Regulatory Standards Knowledge",
                "Environmental Audits",
                "Permitting Process",
                "Pollution Control",
                "Sustainability Reporting",
                "Ecosystem Management",
                "Waste Management",
                "Compliance Training",
                "Environmental Impact Assessment",
                "Safety Management"
            ],
            "Geoscience" => [
                "Geological Mapping",
                "Mineral Exploration",
                "Seismic Interpretation",
                "Hydrogeology",
                "Environmental Geology",
                "Geochemistry",
                "Remote Sensing",
                "Paleontology",
                "Petrology",
                "Geophysics"
            ],
            "Energy Policy" => [
                "Policy Analysis and Development",
                "Regulatory Affairs",
                "Sustainable Energy Strategies",
                "Stakeholder Engagement",
                "Climate Change Impacts",
                "Legislative Processes",
                "Energy Market Dynamics",
                "Renewable Energy Incentives",
                "Environmental Law",
                "Public Policy Advocacy"
            ],
            "Network Architecture" => [
                "Network Design and Implementation",
                "Advanced Routing and Switching",
                "Load Balancing and Redundancy",
                "Network Security Solutions",
                "Cloud Networking",
                "Wireless Network Design",
                "Network Performance Optimization",
                "IP Addressing and Subnetting",
                "Software-Defined Networking",
                "Network Troubleshooting"
            ],
            "Telecom Engineering" => [
                "Telecommunication Systems",
                "Signal Processing",
                "Network Infrastructure",
                "Wireless Technologies",
                "Fiber Optic Technology",
                "Circuit Design and Testing",
                "Spectrum Management",
                "Telecom Standards and Protocols",
                "Project Management",
                "Quality Control"
            ],
            "Wireless Communication" => [
                "Wireless Network Design",
                "RF Planning and Optimization",
                "Cellular Technologies (LTE, 5G)",
                "Wireless Protocols and Standards",
                "Antenna Design",
                "Signal Processing",
                "Mobile Communication Systems",
                "Wireless Security",
                "IoT Connectivity",
                "Network Performance Analysis"
            ],
            "Satellite Communication" => [
                "Satellite Orbit Mechanics",
                "Link Budget Analysis",
                "Antenna and Transponder Design",
                "Signal Processing",
                "Satellite Navigation Systems",
                "Ground Station Operations",
                "Satellite Launch and Deployment",
                "Frequency Coordination",
                "Space Communication Protocols",
                "Remote Sensing"
            ],
            "Fiber Optics Engineering" => [
                "Fiber Optic Cable Design",
                "Optical Network Deployment",
                "Splicing and Connectors",
                "Signal Transmission Principles",
                "DWDM Systems",
                "Troubleshooting and Maintenance",
                "Optical Measurement Techniques",
                "Network Planning",
                "Safety Standards",
                "Emerging Fiber Technologies"
            ],
            "Radio Frequency Engineering" => [
                "RF Circuit Design",
                "Antenna Design and Testing",
                "Electromagnetic Field Theory",
                "Wireless System Integration",
                "Spectrum Analysis",
                "Interference Mitigation",
                "Microwave Engineering",
                "RF Safety Standards",
                "Propagation Modeling",
                "Frequency Allocation"
            ],
            "Network Security" => [
                "Firewall Configuration and Management",
                "Intrusion Detection and Prevention",
                "VPN and Encryption Technologies",
                "Security Protocols",
                "Threat Analysis",
                "Penetration Testing",
                "Cybersecurity Frameworks",
                "Network Monitoring",
                "Incident Response",
                "Compliance and Auditing"
            ],
            "Broadband Systems" => [
                "High-Speed Network Infrastructure",
                "Cable and DSL Technologies",
                "Network Configuration",
                "Data Transmission Technologies",
                "Quality of Service (QoS)",
                "Broadband Network Security",
                "Wireless Broadband Solutions",
                "Fiber to the Home (FTTH)",
                "Network Scalability",
                "Regulatory Standards"
            ],
            "Mobile Network Management" => [
                "Mobile Network Infrastructure",
                "Cellular Network Optimization",
                "4G/5G Technologies",
                "Radio Access Network (RAN) Management",
                "Network Traffic Management",
                "Mobile Security",
                "Quality of Service (QoS)",
                "Mobile Device Management",
                "Service Delivery Platforms",
                "IoT Connectivity"
            ],
            "Telecom Regulation" => [
                "Telecommunications Law",
                "Policy and Regulation Development",
                "Compliance Monitoring",
                "Spectrum Management",
                "International Telecommunications Standards",
                "Regulatory Affairs",
                "Consumer Rights and Protection",
                "Telecom Licensing",
                "Interconnection Agreements",
                "Data Privacy and Security"
            ],
            "Clinical Research" => [
                "Clinical Trial Design",
                "Regulatory Compliance",
                "Data Management",
                "Statistical Analysis",
                "Protocol Development",
                "Patient Recruitment",
                "Ethical Considerations",
                "Good Clinical Practice (GCP)",
                "Safety Monitoring",
                "Clinical Study Reports"
            ],
            "Pharmaceutical Sales" => [
                "Product Knowledge",
                "Sales Strategy and Planning",
                "Client Relationship Management",
                "Regulatory Compliance",
                "Market Analysis",
                "Presentation Skills",
                "Negotiation and Closing",
                "Territory Management",
                "Healthcare System Understanding",
                "Sales Reporting"
            ],
            "Medicinal Chemistry" => [
                "Drug Design and Synthesis",
                "Chemical Analysis",
                "Pharmacology",
                "Toxicology",
                "Biochemistry",
                "Molecular Modeling",
                "Chromatography and Spectroscopy",
                "Drug Delivery Systems",
                "Organic Chemistry",
                "Regulatory Knowledge"
            ],
            "Drug Development" => [
                "Preclinical Research",
                "Clinical Trials",
                "Regulatory Submissions",
                "Pharmacokinetics and Pharmacodynamics",
                "Project Management",
                "Quality Assurance",
                "Biostatistics",
                "Therapeutic Area Knowledge",
                "Intellectual Property",
                "Patient Safety"
            ],
            "Regulatory Affairs" => [
                "Regulatory Submissions",
                "Compliance with FDA/EMA Regulations",
                "Labeling and Promotion",
                "Quality Control Standards",
                "Drug Approval Process",
                "Clinical Trial Applications",
                "Regulatory Strategy Development",
                "Post-Market Surveillance",
                "Global Regulatory Requirements",
                "Auditing and Inspection"
            ],
            "Pharmacovigilance" => [
                "Adverse Event Reporting",
                "Drug Safety Monitoring",
                "Risk Management Plans",
                "Regulatory Compliance",
                "Safety Database Management",
                "Signal Detection",
                "Clinical Trial Safety",
                "Epidemiological Studies",
                "Medical Writing",
                "Post-Marketing Surveillance"
            ],
            "Quality Assurance" => [
                "Quality Control Procedures",
                "GMP Compliance",
                "Process Validation",
                "Document Management",
                "Auditing",
                "Batch Record Review",
                "Risk Management",
                "Supplier Quality",
                "Quality Metrics",
                "Regulatory Inspections"
            ],
            "Biotechnology" => [
                "Molecular Biology Techniques",
                "Genetic Engineering",
                "Cell Culture",
                "Protein Purification",
                "Bioinformatics",
                "Bioprocess Engineering",
                "Immunology",
                "Regulatory Compliance",
                "Patent Application",
                "Clinical Trials"
            ],
            "Pharmacy Management" => [
                "Pharmaceutical Dispensing",
                "Inventory Management",
                "Regulatory Compliance",
                "Patient Counseling",
                "Insurance Claims",
                "Pharmacy Operations",
                "Financial Management",
                "Staff Supervision",
                "Clinical Services",
                "Quality Assurance"
            ],
            "Toxicology" => [
                "Risk Assessment",
                "Chemical Analysis",
                "Biomarkers",
                "In Vivo and In Vitro Testing",
                "Regulatory Guidelines",
                "Exposure Assessment",
                "Toxicological Research",
                "Environmental Toxicology",
                "Pharmacokinetics",
                "Clinical Toxicology"
            ]
        ];

        $specializations = Specialization::all();
        foreach ($specializations as $specializationObj) {
            $specializationName = $specializationObj->name;
            if (isset($skills[$specializationName])) {
                foreach ($skills[$specializationName] as $skillName) {
                    Skill::create([
                        'name' => $skillName,
                        'specialization_id' => $specializationObj->id
                    ]);
                }
            }
        }
        foreach ($skills['General'] as $generalSkill) {
            Skill::create([
                'name' => $generalSkill,

            ]);
        }
    }
}
