<?php

namespace Database\Seeders;

use App\Models\Industry;
use App\Models\Skill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SkillsTableSeeder extends Seeder
{
    public function run()
    {
        $skills = [
            "Technology" => [
                "Software Development",
                "Web Development",
                "Mobile Development",
                "Cloud Computing",
                "Artificial Intelligence",
                "Data Science",
                "Database Management",
                "Network Security",
                "Information Technology",
                "Systems Engineering",
                "DevOps",
                "IT Support",
                "Cybersecurity",
                "Computer Hardware",
                "Computer Networking",
            ],
            "Healthcare" => [
                "Nursing",
                "Medical Assisting",
                "Medical Billing and Coding",
                "Medical Technology",
                "Medical Transcription",
                "Pharmacy Technology",
                "Physical Therapy",
                "Occupational Therapy",
                "Radiologic Technology",
                "Dental Assisting",
                "Dental Hygiene",
                "Veterinary Technology",
                "Healthcare Administration",
                "Healthcare Management",
                "Healthcare Finance",
            ],

            "Finance" => [
                "Financial Analysis",
                "Investment Banking",
                "Accounting",
                "Risk Management",
                "Portfolio Management",
                "Financial Planning",
                "Auditing",
                "Taxation",
                "Banking Operations",
                "Asset Management",
                "Corporate Finance",
                "Credit Analysis",
                "Wealth Management",
                "Financial Modeling",
                "Hedge Fund Management",
            ],
            "Education" => [
                "Curriculum Development",
                "Classroom Management",
                "Educational Technology",
                "Lesson Planning",
                "Special Education",
                "Early Childhood Education",
                "E-Learning",
                "Student Assessment",
                "Literacy Instruction",
                "Multilingual Education",
                "Educational Research",
                "School Counseling",
                "Educational Leadership",
                "Adult Education",
                "STEM Education",
            ],
            "Manufacturing" => [
                "Lean Manufacturing",
                "Six Sigma",
                "Quality Control",
                "Supply Chain Management",
                "Product Development",
                "Manufacturing Engineering",
                "Process Improvement",
                "Industrial Automation",
                "Production Planning",
                "Materials Management",
                "Continuous Improvement",
                "Safety Management",
                "Operations Management",
                "CNC Machining",
                "Robotics",
            ],
            "Retail" => [
                "Visual Merchandising",
                "Inventory Management",
                "Customer Service",
                "Retail Sales",
                "E-commerce",
                "Loss Prevention",
                "Store Management",
                "Retail Marketing",
                "Retail Analytics",
                "Retail Operations",
                "Supply Chain",
                "Vendor Management",
                "Category Management",
                "Store Design",
                "Retail Finance",
            ],
            "Construction" => [
                "Project Management",
                "Civil Engineering",
                "Structural Engineering",
                "Construction Management",
                "Architectural Design",
                "Building Codes",
                "Surveying",
                "Cost Estimation",
                "Safety Compliance",
                "Contract Negotiation",
                "Green Building",
                "HVAC Systems",
                "Construction Materials",
                "Construction Equipment",
                "Blueprint Reading",
            ],
            "Agriculture" => [
                "Crop Management",
                "Soil Science",
                "Pest Control",
                "Irrigation Systems",
                "Sustainable Agriculture",
                "Livestock Management",
                "Agribusiness",
                "Horticulture",
                "Agricultural Economics",
                "Farm Equipment Operation",
                "Organic Farming",
                "Aquaculture",
                "Agricultural Research",
                "Precision Farming",
                "Agricultural Marketing",
            ],
            "Energy" => [
                "Renewable Energy",
                "Energy Efficiency",
                "Power Generation",
                "Energy Policy",
                "Electrical Engineering",
                "Oil and Gas Exploration",
                "Nuclear Energy",
                "Energy Trading",
                "Environmental Compliance",
                "Energy Storage",
                "Smart Grid Technology",
                "Geothermal Energy",
                "Solar Energy",
                "Wind Energy",
                "Energy Auditing",
            ],
            "Transportation" => [
                "Logistics Management",
                "Fleet Management",
                "Aviation",
                "Maritime Operations",
                "Public Transit Planning",
                "Rail Transportation",
                "Supply Chain Optimization",
                "Automotive Engineering",
                "Aviation Maintenance",
                "Traffic Engineering",
                "Transportation Safety",
                "Air Traffic Control",
                "Shipping and Cargo",
                "Transportation Modeling",
                "Transportation Policy",
            ],
            "Hospitality" => [
                "Hotel Management",
                "Restaurant Management",
                "Hospitality Marketing",
                "Event Planning",
                "Customer Relations",
                "Food Service",
                "Tourism Management",
                "Hospitality Finance",
                "Resort Operations",
                "Front Office Management",
                "Culinary Arts",
                "Spa Management",
                "Hotel Sales",
                "Revenue Management",
                "Hotel Design and Layout",
            ],
            "Real Estate" => [
                "Property Management",
                "Real Estate Investment",
                "Commercial Real Estate",
                "Residential Sales",
                "Real Estate Appraisal",
                "Real Estate Development",
                "Leasing and Negotiation",
                "Real Estate Finance",
                "Real Estate Law",
                "Land Use Planning",
                "Real Estate Marketing",
                "Property Valuation",
                "Property Taxation",
                "Real Estate Brokerage",
                "Real Estate Analytics",
            ],
            "Media" => [
                "Journalism",
                "Digital Marketing",
                "Public Relations",
                "Broadcast Media",
                "Content Creation",
                "Video Production",
                "Social Media Management",
                "Advertising",
                "Media Planning",
                "Film Editing",
                "News Writing",
                "Multimedia Storytelling",
                "Audio Production",
                "Photography",
                "Media Ethics",
            ],
            "Telecommunications" => [
                "Network Engineering",
                "Telecommunications Infrastructure",
                "Mobile Communications",
                "VoIP Technology",
                "Data Center Management",
                "Wireless Networking",
                "Fiber Optics",
                "Telecommunications Security",
                "Satellite Communication",
                "Telecom Policy and Regulation",
                "Broadband Technology",
                "Telecommunications Software",
                "Network Optimization",
                "Telecommunications Project Management",
                "IoT Connectivity",
            ],
            "Pharmaceuticals" => [
                "Drug Discovery",
                "Pharmaceutical Manufacturing",
                "Regulatory Affairs",
                "Clinical Research",
                "Pharmacology",
                "Quality Control",
                "Pharmaceutical Sales",
                "Pharmaceutical Marketing",
                "Pharmacy Operations",
                "Biotechnology",
                "Clinical Trials",
                "Pharmaceutical Chemistry",
                "Pharmaceutical Distribution",
                "Pharmaceutical Packaging",
                "Pharmaceutical Quality Assurance",
            ],
            "Consulting" => [
                "Management Consulting",
                "Strategy Consulting",
                "Financial Consulting",
                "Human Resources Consulting",
                "IT Consulting",
                "Marketing Consulting",
                "Operations Consulting",
                "Healthcare Consulting",
                "Environmental Consulting",
                "Legal Consulting",
                "Business Process Consulting",
                "Organizational Consulting",
                "Change Management Consulting",
                "Data Analytics Consulting",
                "Technology Consulting",
            ],
            "Fashion" => [
                "Fashion Design",
                "Apparel Merchandising",
                "Fashion Styling",
                "Fashion Marketing",
                "Textile Design",
                "Fashion Illustration",
                "Pattern Making",
                "Sewing and Tailoring",
                "Fashion Retailing",
                "Fashion Photography",
                "Footwear Design",
                "Jewelry Design",
                "Fashion Show Production",
                "Fashion Buying",
                "Sustainable Fashion",
            ],
            "Food & Beverage" => [
                "Culinary Arts",
                "Food Service Management",
                "Baking and Pastry",
                "Restaurant Operations",
                "Food Safety and Hygiene",
                "Sommelier",
                "Beverage Management",
                "Food Production",
                "Catering Services",
                "Menu Planning",
                "Wine Tasting",
                "Nutrition and Dietetics",
                "Bartending",
                "Hospitality and Tourism",
                "Gastronomy",
            ],
            "Legal" => [
                "Litigation",
                "Corporate Law",
                "Criminal Law",
                "Intellectual Property Law",
                "Environmental Law",
                "Family Law",
                "Real Estate Law",
                "Tax Law",
                "Labor and Employment Law",
                "Healthcare Law",
                "Immigration Law",
                "Contract Law",
                "Banking and Finance Law",
                "International Law",
                "Civil Rights Law",
            ],
            "Environmental Services" => [
                "Environmental Consulting",
                "Sustainability",
                "Environmental Policy",
                "Ecology",
                "Climate Change Adaptation",
                "Environmental Impact Assessment",
                "Renewable Energy",
                "Waste Management",
                "Natural Resource Management",
                "Environmental Education",
                "Air Quality Management",
                "Water Resource Management",
                "Conservation Biology",
                "Green Building Design",
                "Soil and Water Testing",
            ],
        ];

        $industries = Industry::all();
        foreach ($industries as $industry) {
            $industryName = $industry->name;
            if (isset($skills[$industryName])) {
                foreach ($skills[$industryName] as $skillName) {
                    Skill::create([
                        'name' => $skillName,
                        'industry_id' => $industry->id
                    ]);
                }
            }
        }
    }
}
